del B-1\boxCount.csv
del B-2\boxCount.csv
del B-3\boxCount.csv
del B-4\boxCount.csv
del B-5\boxCount.csv
del B-6\boxCount.csv
del B-7\boxCount.csv
del B-8\boxCount.csv
del B-9\boxCount.csv
del B-10\boxCount.csv
del B-11\boxCount.csv
del B-12\boxCount.csv
del B-13\boxCount.csv
del B-14\boxCount.csv
del B-15\boxCount.csv
del B-16\boxCount.csv
del B-17\boxCount.csv
del B-18\boxCount.csv
del B-19\boxCount.csv
del B-20\boxCount.csv
del B-21\boxCount.csv
del B-22\boxCount.csv
del B-1\box.vtk
del B-2\box.vtk
del B-3\box.vtk
del B-4\box.vtk
del B-5\box.vtk
del B-6\box.vtk
del B-7\box.vtk
del B-8\box.vtk
del B-9\box.vtk
del B-10\box.vtk
del B-11\box.vtk
del B-12\box.vtk
del B-13\box.vtk
del B-14\box.vtk
del B-15\box.vtk
del B-16\box.vtk
del B-17\box.vtk
del B-18\box.vtk
del B-19\box.vtk
del B-20\box.vtk
del B-21\box.vtk
del B-22\box.vtk
del B-1\boxInitialRadius.csv
del B-2\boxInitialRadius.csv
del B-3\boxInitialRadius.csv
del B-4\boxInitialRadius.csv
del B-5\boxInitialRadius.csv
del B-6\boxInitialRadius.csv
del B-7\boxInitialRadius.csv
del B-8\boxInitialRadius.csv
del B-9\boxInitialRadius.csv
del B-10\boxInitialRadius.csv
del B-11\boxInitialRadius.csv
del B-12\boxInitialRadius.csv
del B-13\boxInitialRadius.csv
del B-14\boxInitialRadius.csv
del B-15\boxInitialRadius.csv
del B-16\boxInitialRadius.csv
del B-17\boxInitialRadius.csv
del B-18\boxInitialRadius.csv
del B-19\boxInitialRadius.csv
del B-20\boxInitialRadius.csv
del B-21\boxInitialRadius.csv
del B-22\boxInitialRadius.csv
del B-1\boxTimeSeries.csv
del B-2\boxTimeSeries.csv
del B-3\boxTimeSeries.csv
del B-4\boxTimeSeries.csv
del B-5\boxTimeSeries.csv
del B-6\boxTimeSeries.csv
del B-7\boxTimeSeries.csv
del B-8\boxTimeSeries.csv
del B-9\boxTimeSeries.csv
del B-10\boxTimeSeries.csv
del B-11\boxTimeSeries.csv
del B-12\boxTimeSeries.csv
del B-13\boxTimeSeries.csv
del B-14\boxTimeSeries.csv
del B-15\boxTimeSeries.csv
del B-16\boxTimeSeries.csv
del B-17\boxTimeSeries.csv
del B-18\boxTimeSeries.csv
del B-19\boxTimeSeries.csv
del B-20\boxTimeSeries.csv
del B-21\boxTimeSeries.csv
del B-22\boxTimeSeries.csv


