boxFlowField – Droplets Simulation
boxFlowField Program
77 statements
Source File
Uses
terminalControler_m
conditionValue_m
unstructuredGrid_m
boxCounter_m
Calls
Contents
Variables
i_box num_box nc caseName box_array bResult mesh
Derived Types
boxResult_t
Subroutines
output_countCSV output_boxVTK
Variables
Type Attributes Name Initial
integer :: i_box
integer :: num_box
integer :: nc
character(len=255) :: caseName
type(boxCounter), allocatable :: box_array(:)
type(boxResult_t), allocatable :: bResult(:)
type(FlowFieldUnstructuredGrid) :: mesh
Derived Types
type :: boxResult_t
Components
Type Visibility Attributes Name Initial
real, public :: flowVelocity(3)
Subroutines
subroutine output_countCSV()
Arguments
None
subroutine output_boxVTK()
Arguments
None
Call graph
boxflowfield calls print_progress, flowfieldunstructuredgrid_withmeshfile, get_box_array, output_boxvtk, output_countcsv, set_formattc
flowfieldunstructuredgrid_withmeshfile calls get_dirfrompath
get_box_array calls read_csv
output_boxvtk calls output, unstructuredgrid_invtk_