cellCenterCalc_test – Droplets Simulation
cellCenterCalc_test Program
35 statements
Source File
Uses
geometry_m
unstructuredGrid_m
セル重心計算がうまく行っているかをテストする。 具体的には、重心をテトラの内外判定にかけている。
Calls
Contents
Variables
grid centers vertices center i imax n
Variables
Type Attributes Name Initial
type(FlowFieldUnstructuredGrid) :: grid
real, allocatable :: centers(:,:)
real, allocatable :: vertices(:,:)
real :: center(3)
integer :: i
integer :: imax
integer :: n
Call graph
cellcentercalc_test calls insidejudgment_tetra, insidejudgment_tetra_check
insidejudgment_tetra calls volume_tetra
insidejudgment_tetra_check calls volume_tetra
volume_tetra calls cross_product
cross_product calls cross_product_dble, cross_product_real