CUBE2USG – Droplets Simulation
CUBE2USG Program
114 statements
Source File
Uses
simpleFile_reader
plot3d_operator
array_m
VTK_operator_m
CUBE格子上の流速場をVTK非構造格子に載せるプログラム。 非構造格子上の各格子に対して、CUBE格子上の最近傍節点を探し、対応付けを行う。 対応する各節点における流速を配列にして、そのままバイナリファイル出力を行う。
Calls
Contents
Variables
F_fname USG_fname casefname filename field_name caseName CorrespondenceFName fileID num_record num_cell nc nc_max velocity USG cubeMesh vtkCell2cubeNode
Subroutines
output_nodeInfo search_nodeInfo read_nodeInfo solve_correspondence
Variables
Type Attributes Name Initial
character(len=100) :: F_fname
character(len=100) :: USG_fname
character(len=100) :: casefname
character(len=50), parameter :: filename = 'name.txt'
character(len=50), allocatable :: field_name(:)
character(len=50), allocatable :: caseName(:)
character(len=20), parameter :: CorrespondenceFName = 'vtkCell2cubeNode.txt'
integer :: fileID
integer :: num_record
integer :: num_cell
integer :: nc
integer :: nc_max
real, allocatable :: velocity(:,:)
type(UnstructuredGrid_inVTK) :: USG
type(Plot3dMesh) :: cubeMesh
type(plot3dNodeInfo), allocatable :: vtkCell2cubeNode(:)
Subroutines
subroutine output_nodeInfo()
対応する節点情報をアスキーファイルで出力するサブルーチン
Arguments
None
subroutine search_nodeInfo()
非構造格子に対応する節点情報を探すサブルーチン
Arguments
None
subroutine read_nodeInfo(success)
節点情報対応付けファイルを読み込むサブルーチン
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: success
subroutine solve_correspondence()
格子と節点の対応付けを解決するサブルーチン
Arguments
None
Call graph
cube2usg calls output_2darray_asbinary, read_plot3d_multigrid, read_textrecord, solve_correspondence
read_plot3d_multigrid calls cubes
solve_correspondence calls output_nodeinfo, read_nodeinfo, search_nodeinfo
output_nodeinfo calls get_cubeshape, get_numcube
read_nodeinfo calls get_cubeshape, get_numcube
search_nodeinfo calls erapsedtime, print_progress, nearestnodeinfo, get_cellcenters, set_formattc, timekeeper_