dropletCount – Droplets Simulation
dropletCount Program
90 statements
Source File
Uses
virusDroplet_m
caseName_m
conditionValue_m
boxCounter_m
ボックスを通過した飛沫をカウントする。 飛沫計算の出力ファイルを順に読み込み、各ボックスに対して内外判定を行う。 ボックス側では、通過した飛沫のIDしか見ておらず、同じIDの飛沫のダブルカウントなどは起こらない。
Calls
Contents
Variables
n i_box num_box caseID caseName_array caseName fname id_array mainDroplets droplets condVal box_array bResult
Derived Types
boxResult_t
Functions
RateOfInfection
Subroutines
output_countCSV output_boxVTK
Variables
Type Attributes Name Initial
integer :: n
integer :: i_box
integer :: num_box
integer :: caseID
character(len=50), allocatable :: caseName_array(:)
character, allocatable :: caseName
character, allocatable :: fname
integer, allocatable :: id_array(:)
type(virusDroplet_t), allocatable :: mainDroplets(:)
type(virusDroplet_t), allocatable :: droplets(:)
type(conditionValue_t) :: condVal
type(boxCounter), allocatable :: box_array(:)
type(boxResult_t), allocatable :: bResult(:)
Derived Types
type :: boxResult_t
Components
Type Visibility Attributes Name Initial
integer, public :: num_droplet
real, public :: volume
real, public :: RoI
Functions
elemental function RateOfInfection(volume)
1分間あたりの感染確率を計算（もとの資料では1時間あたりの感染確率だが、1分間あたりに換算）
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: volume
Return Value real
Subroutines
subroutine output_countCSV()
Arguments
None
subroutine output_boxVTK()
Arguments
None
Call graph
dropletcount calls case_check, dropletidinbox, output_countcsv, read_condition, read_backup, get_box_array, droplettotalvolume, rateofinfection, output_boxvtk
case_check calls read_textrecord
get_box_array calls read_csv
output_boxvtk calls unstructuredgrid_invtk_