geometry_test – Droplets Simulation
geometry_test Program
25 statements
Source File
Uses
geometry_m
テトラ内外判定をテストする。 乱数で発生させた点群に対して判定を行う。 テスト用のテトラは単純な形状で、平面の方程式から即座に内外判定が行えるので、これと比較してテストする。
Calls
Contents
Variables
tetra imax rand point plane_judge tetra_judge i
Functions
plane_equation
Variables
Type Attributes Name Initial
real, parameter :: tetra(3,4) = reshape([0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.], shape(tetra))
integer, parameter :: imax = 10000
real :: rand(3,imax)
real :: point(3)
logical :: plane_judge
logical :: tetra_judge
integer :: i
Functions
function plane_equation(x, y) result(z)
テスト用テトラの斜面の方程式
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
real, intent(in) :: y
Return Value real
Call graph
geometry_test calls plane_equation, insidejudgment_tetra
insidejudgment_tetra calls volume_tetra
volume_tetra calls cross_product
cross_product calls cross_product_dble, cross_product_real