kdTree_test – Droplets Simulation
kdTree_test Program
49 statements
Source File
Uses
unstructuredGrid_m
kdTree_m
path_operator_m
kdTreeによる探索結果と、厳密なnearest探索結果が一致するかどうかをテスト
Calls
Contents
Variables
grid xyz kd_tree iimx vtkFName kd_treeFName output_dir existance
Subroutines
test
Variables
Type Attributes Name Initial
type(FlowFieldUnstructuredGrid) :: grid
real, allocatable :: xyz(:,:)
type(kdTree) :: kd_tree
integer :: iimx
character(len=:), allocatable :: vtkFName
character(len=:), allocatable :: kd_treeFName
character(len=10), parameter :: output_dir = 'test_check'
logical :: existance
Subroutines
subroutine test()
乱数で発生させた点に対して、kdTreeによる探索結果と、厳密なnearest探索結果が一致するかどうかをテスト
Arguments
None
Call graph
kdtree_test calls kdtree_, make_directory, test
kdtree_ calls print_progress, node, merge_sort, real2content, set_formattc
make_directory calls replace_str
test calls get_minmaxofgrid, nearest_search_exact, search