MAIN – Droplets Simulation
MAIN Program
14 statements
Source File
Uses
caseName_m
dropletMotionSimulation
Simulation of Virus-Laden Droplets Behavior in AFDET by KIYOTA OGURA(2021/1/10) updated by YUTA IDA
Calls
Contents
Variables
caseName caseID
Variables
Type Attributes Name Initial
character(len=50), allocatable :: caseName(:)
integer :: caseID
Call graph
main calls read_basicsettingonsimulation, output_resultsummary, case_check, simulationsetup, maindropletloop
output_resultsummary calls nowdateandtime
case_check calls read_textrecord
simulationsetup calls flowfield_, read_condition, dropletgenerator_, dropletequationsolver_, read_backup
flowfield_ calls flowfieldunstructuredgrid_
dropletequationsolver_ calls basicparameter_
flowfieldunstructuredgrid_ calls get_dirfrompath