sort_main_vtk_ver – Droplets Simulation
sort_main_vtk_ver Program
44 statements
Source File
Uses
path_operator_m
kdTree_m
unstructuredGrid_m
Calls
Contents
Variables
grid xyz kd_tree droplet_position nearest_ID n_unit i iimx nearestID vtkFName output_dir kdTree_startTime kdTree_endTime fullSearch_startTime fullSearch_endTime
Variables
Type Attributes Name Initial
type(FlowFieldUnstructuredGrid) :: grid
real, allocatable :: xyz(:,:)
type(kdTree) :: kd_tree
real :: droplet_position(3)
integer :: nearest_ID
integer :: n_unit
integer :: i
integer :: iimx
integer :: nearestID
character, allocatable :: vtkFName
character(len=10), parameter :: output_dir = 'test_check'
real :: kdTree_startTime
real :: kdTree_endTime
real :: fullSearch_startTime
real :: fullSearch_endTime
Call graph
sort_main_vtk_ver calls make_directory, kdtree_
make_directory calls replace_str
kdtree_ calls real2content, heap_sort