sort_test – Droplets Simulation
sort_test Program
51 statements
Source File
Uses
sort_m
array_m
ヒープソートの機能テスト
Calls
Contents
Variables
test1 test2 test3
Subroutines
test_sort
Variables
Type Attributes Name Initial
real, parameter :: test1(10) = [-9.0, -1.0, 0.0, 3.0, 5.0, 7.2, 14.4, 99.9, 122.5, 255.0]
real, parameter :: test2(11) = [-99.0, -9.0, -1.0, 0.0, 3.0, 5.0, 7.2, 14.4, 99.9, 122.5, 255.0]
real :: test3(10000)
Subroutines
subroutine test_sort(array_correct, sort_mode)
正解配列（ソート済み配列）を引数に取り、それをシャッフルしたのちにソートを行う 正解配列とソート後の配列を比較し、ソートが機能しているかを検証
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: array_correct(:)
character, intent(in) :: sort_mode
Call graph
sort_test calls test_sort
test_sort calls fisheryates_shuffle, real2content, merge_sort, heap_sort