translate – Droplets Simulation
translate Program
Hikaru Konishi
60 statements
Source File
Uses
virusDroplet_m
caseName_m
全飛沫に対して、基準点をbefore_dGroupCenter、回転軸をrotation_axisとして、反時計回りにphi[rad]だけ回転させる。 回転後の飛沫中心をafter_dGroupCenterに平行移動させる。
Calls
Contents
Variables
droplets caseName_array caseName fnameDecoration before_dGroupCenter after_dGroupCenter rotation_axis rotation_angle_deg i n_unit PI vec center_displacement phi
Variables
Type Attributes Name Initial
type(virusDroplet_t), allocatable :: droplets(:)
character(len=50), allocatable :: caseName_array(:)
character, allocatable :: caseName
character(len=15) :: fnameDecoration
double precision :: before_dGroupCenter(3)
double precision :: after_dGroupCenter(3)
character(len=1) :: rotation_axis
double precision :: rotation_angle_deg
integer :: i
integer :: n_unit
double precision, parameter :: PI = acos(-1.d0)
double precision :: vec(3)
double precision :: center_displacement(3)
double precision :: phi
Call graph
translate calls case_check, read_backup, output_backup, output_droplet_vtk
case_check calls read_textrecord