case_check – Droplets Simulation
case_check Subroutine
22 statements
Source File
public subroutine case_check(caseName_array)
Uses
simpleFile_reader
case名をキーボードから取得する。 TXTファイルを指定すると、それを全行読み込んで配列に格納。
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(out), allocatable :: caseName_array(:)
Calls
Called by
Contents
Call graph
case_check calls read_textrecord
dropletcount calls case_check
main calls case_check
translate calls case_check