cross_product_real – Droplets Simulation
cross_product_real Function
7 statements
Source File
public function cross_product_real(a, b) result(cross)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: a(3)
real, intent(in) :: b(3)
Return Value real(3)
Called by
Contents
None
Call graph
cross_product calls cross_product_real
volume_tetra calls cross_product
insidejudgment_tetra calls volume_tetra
insidejudgment_tetra_check calls volume_tetra
geometry_test calls insidejudgment_tetra
cellcentercalc_test calls insidejudgment_tetra, insidejudgment_tetra_check