EC_Scalar_reader – Droplets Simulation
EC_Scalar_reader Subroutine
36 statements
Source File
public subroutine EC_Scalar_reader(scalar, unit, is_end)
Arguments
Type Intent Optional Attributes Name
type(EC_Scalar_t) :: scalar
integer(kind=4), intent(in) :: unit
logical, intent(out) :: is_end
Calls
Called by
Contents
None
Call graph
ec_scalar_reader calls get_data_char_, get_data_array_float64_, get_data_int32_
read_fph_main_data calls ec_scalar_reader
read_scf_file calls read_fph_main_data