EC_Vector_reader – Droplets Simulation
EC_Vector_reader Subroutine
39 statements
Source File
public subroutine EC_Vector_reader(vector, unit, is_end)
Arguments
Type Intent Optional Attributes Name
type(EC_Vector_t) :: vector
integer(kind=4), intent(in) :: unit
logical, intent(out) :: is_end
Calls
Called by
Contents
None
Call graph
ec_vector_reader calls ignore_data_, get_data_array_float64_, get_data_char_, get_data_int32_
read_fph_main_data calls ec_vector_reader
read_scf_file calls read_fph_main_data