FlowField_ – Droplets Simulation
FlowField_ Function
33 statements
Source File
public function FlowField_(time, PATH2FlowFile, DeltaT, OFFSET, outputINTERVAL, LoopHead, LoopTail, meshFile) result(flow_field)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: time
現在無次元時刻
character(len=*), intent(in) :: PATH2FlowFile
double precision, intent(in) :: DeltaT
流体計算の時間間隔
integer, intent(in) :: OFFSET
integer, intent(in) :: outputINTERVAL
integer, intent(in) :: LoopHead
integer, intent(in) :: LoopTail
character(len=*), intent(in), optional :: meshFile
Return Value type(FlowField)
Calls
Contents
Call graph
flowfield_ calls get_requiredfilename, flowfieldunstructuredgrid_, flowfieldunstructuredgrid_withmeshfile, set_time
flowfieldunstructuredgrid_ calls get_dirfrompath
flowfieldunstructuredgrid_withmeshfile calls get_dirfrompath