FlowFieldUnstructuredGrid_ – Droplets Simulation
FlowFieldUnstructuredGrid_ Function
14 statements
Source File
public function FlowFieldUnstructuredGrid_(FlowFieldFile, meshFile)
Uses
path_operator_m
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: FlowFieldFile
character, intent(in), optional :: meshFile
Return Value type(FlowFieldUnstructuredGrid)
Calls
Called by
Contents
None
Call graph
flowfieldunstructuredgrid_ calls get_dirfrompath
flowfield_ calls flowfieldunstructuredgrid_
boxflowfield calls flowfieldunstructuredgrid_
simulationsetup calls flowfield_
main calls simulationsetup