get_data_array_float64_ – Droplets Simulation
get_data_array_float64_ Subroutine
25 statements
Source File
public subroutine get_data_array_float64_(unit, ret_array, ret_array_size)
倍精度実数型配列の読み込み
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(in) :: unit
real(kind=4), intent(out), allocatable :: ret_array(:)
integer(kind=4), intent(in) :: ret_array_size
Called by
Contents
None
Call graph
read_fph_main_data calls get_data_array_float64_, ec_scalar_reader, fc_vector_reader, fc_scalar_reader, ec_vector_reader
ec_scalar_reader calls get_data_array_float64_
fc_vector_reader calls get_data_array_float64_
fc_scalar_reader calls get_data_array_float64_
ec_vector_reader calls get_data_array_float64_
read_scf_file calls read_fph_main_data