get_data_int32_ – Droplets Simulation
get_data_int32_ Subroutine
8 statements
Source File
public subroutine get_data_int32_(unit, retval)
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(in) :: unit
integer(kind=4), intent(inout) :: retval
Called by
Contents
None
Call graph
ec_scalar_reader calls get_data_int32_
fc_vector_reader calls get_data_int32_
read_fph_main_data calls get_data_int32_, ec_scalar_reader, fc_vector_reader, ec_vector_reader, fc_scalar_reader
read_fph_header_data calls get_data_int32_
ec_vector_reader calls get_data_int32_
fc_scalar_reader calls get_data_int32_
read_scf_file calls read_fph_main_data, read_fph_header_data