get_DirFromPath – Droplets Simulation
get_DirFromPath Subroutine
23 statements
Source File
public subroutine get_DirFromPath(path, directory, filename)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: path
character, intent(out), allocatable :: directory
character, intent(out), optional allocatable :: filename
Called by
Contents
None
Call graph
flowfieldunstructuredgrid_ calls get_dirfrompath
flowfield_ calls flowfieldunstructuredgrid_
boxflowfield calls flowfieldunstructuredgrid_
simulationsetup calls flowfield_
main calls simulationsetup