get_data_array_int32_ – Droplets Simulation
get_data_array_int32_ Subroutine
24 statements
Source File
public subroutine get_data_array_int32_(unit, ret_array, ret_array_size)
整数型配列の読み込み
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(in) :: unit
integer(kind=4), intent(out), allocatable :: ret_array(:)
integer(kind=4), intent(in) :: ret_array_size
Called by
Contents
None
Call graph
read_fph_main_data calls get_data_array_int32_, fc_scalar_reader, fc_vector_reader
fc_scalar_reader calls get_data_array_int32_
fc_vector_reader calls get_data_array_int32_
read_scf_file calls read_fph_main_data