get_box_array – Droplets Simulation
get_box_array Function
22 statements
Source File
public function get_box_array(dir, num_Flag) result(new_box_array)
Uses
simpleFile_reader
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: dir
integer, intent(in) :: num_Flag
Return Value type(boxCounter),allocatable,(:)
Calls
Called by
Contents
None
Call graph
get_box_array calls read_csv
boxflowfield calls get_box_array
dropletcount calls get_box_array