insideJudgment_tetra – Droplets Simulation
insideJudgment_tetra Function
8 statements
Source File
public function insideJudgment_tetra(vertices, point) result(isInside)
任意の点がテトラの内部にあるかどうかを判定する。 点でテトラを分割したそれぞれの体積の和が、元々のテトラの体積を上回れば、点はテトラ外部にある。 https://matcha-choco010.net/2018/03/14/point-in-tetrahedron/
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: vertices(3,4)
real, intent(in) :: point(3)
Return Value logical
Calls
Called by
Contents
None
Call graph
insidejudgment_tetra calls volume_tetra
volume_tetra calls cross_product
cross_product calls cross_product_dble, cross_product_real
geometry_test calls insidejudgment_tetra
cellcentercalc_test calls insidejudgment_tetra