insideJudgment_tetra_check – Droplets Simulation
insideJudgment_tetra_check Subroutine
7 statements
Source File
public subroutine insideJudgment_tetra_check(vertices, point, vol_sum, volume)
テトラの内外判定の内部処理確認用サブルーチン
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: vertices(3,4)
real, intent(in) :: point(3)
real, intent(out) :: vol_sum
分割体積和
real, intent(out) :: volume
テトラ体積
Calls
Called by
Contents
Call graph
insidejudgment_tetra_check calls volume_tetra
volume_tetra calls cross_product
cellcentercalc_test calls insidejudgment_tetra_check