read_SCF_file – Droplets Simulation
read_SCF_file Subroutine
13 statements
Source File
public subroutine read_SCF_file(this, filename)
Type Bound
scf_grid_t
Arguments
Type Intent Optional Attributes Name
class(scf_grid_t), intent(inout) :: this
character(len=*), intent(in) :: filename
Calls
Contents
Call graph
read_scf_file calls destructor, open_binary_sequential_, read_fph_header_data, read_fph_main_data
read_fph_header_data calls get_data_float64_, get_data_int32_
read_fph_main_data calls ec_scalar_reader, ec_vector_reader, fc_scalar_reader, fc_vector_reader, get_data_array_float64_, get_data_array_int32_, get_data_char_, get_data_int32_
ec_scalar_reader calls get_data_array_float64_, get_data_char_, get_data_int32_
ec_vector_reader calls get_data_array_float64_, get_data_char_, get_data_int32_, ignore_data_
fc_scalar_reader calls get_data_array_float64_, get_data_array_int32_, get_data_char_, get_data_int32_
fc_vector_reader calls get_data_array_float64_, get_data_array_int32_, get_data_char_, get_data_int32_, ignore_data_