read_textRecord – Droplets Simulation
read_textRecord Subroutine
15 statements
Source File
public subroutine read_textRecord(filename, array)
TXTファイルを、全行読み込む。 1行あたりの文字数は引数に依存。
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
ファイル名（パス）
character(len=*), intent(out), allocatable :: array(:)
文字列配列 要素数はallocatableだが、1要素あたりの文字数は予め指定
Called by
Contents
Call graph
case_check calls read_textrecord
cube2usg calls read_textrecord
dropletcount calls case_check
main calls case_check
translate calls case_check