read_FPH_Main_data – Droplets Simulation
read_FPH_Main_data Subroutine
198 statements
Source File
public subroutine read_FPH_Main_data(unit, CAN_X, CAN_Y, CAN_Z, CCE_X, CCE_Y, CCE_Z, EC_Scalars, EC_Vectors, FC_Scalars, FC_Vectors, EC_Scalar_cnt, EC_Vector_cnt, FC_Scalar_cnt, FC_Vector_cnt, NODES, NFACE, NELEM, NDTOT, IE1, IE2, NDNUM, IDNO)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
real(kind=4), intent(inout), allocatable :: CAN_X(:)
real(kind=4), intent(inout), allocatable :: CAN_Y(:)
real(kind=4), intent(inout), allocatable :: CAN_Z(:)
real(kind=4), intent(inout), allocatable :: CCE_X(:)
real(kind=4), intent(inout), allocatable :: CCE_Y(:)
real(kind=4), intent(inout), allocatable :: CCE_Z(:)
type(EC_Scalar_t), intent(inout), allocatable :: EC_Scalars(:)
type(EC_Vector_t), intent(inout), allocatable :: EC_Vectors(:)
type(FC_Scalar_t), intent(inout), allocatable :: FC_Scalars(:)
type(FC_Vector_t), intent(inout), allocatable :: FC_Vectors(:)
integer, intent(inout) :: EC_Scalar_cnt
integer, intent(inout) :: EC_Vector_cnt
integer, intent(inout) :: FC_Scalar_cnt
integer, intent(inout) :: FC_Vector_cnt
integer, intent(inout) :: NODES
integer, intent(inout) :: NFACE
integer, intent(inout) :: NELEM
integer, intent(inout) :: NDTOT
integer, intent(inout), allocatable :: IE1(:)
integer, intent(inout), allocatable :: IE2(:)
integer, intent(inout), allocatable :: NDNUM(:)
integer, intent(inout), allocatable :: IDNO(:)
Calls
Called by
Contents
None
Call graph
read_fph_main_data calls get_data_int32_, fc_scalar_reader, get_data_array_int32_, ec_vector_reader, get_data_char_, get_data_array_float64_, ec_scalar_reader, fc_vector_reader
fc_scalar_reader calls get_data_int32_, get_data_array_int32_, get_data_char_, get_data_array_float64_
ec_vector_reader calls get_data_int32_, get_data_char_, get_data_array_float64_, ignore_data_
ec_scalar_reader calls get_data_int32_, get_data_char_, get_data_array_float64_
fc_vector_reader calls get_data_int32_, get_data_array_int32_, get_data_char_, get_data_array_float64_, ignore_data_
read_scf_file calls read_fph_main_data