read_backup – Droplets Simulation
read_backup Function
13 statements
Source File
public function read_backup(fname) result(dGroup_read)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: fname
Return Value type(DropletGroup)
Called by
Contents
None
Call graph
simulationsetup calls read_backup
translate calls read_backup
droplet2csv calls read_backup
dropletcount calls read_backup
main calls simulationsetup