search_nodeInfo – Droplets Simulation
search_nodeInfo Subroutine
21 statements
Source File
subroutine search_nodeInfo()
Uses
terminalControler_m
timeKeeper_m
unstructuredElement_m
非構造格子に対応する節点情報を探すサブルーチン
Arguments
None
Calls
Called by
Contents
None
Call graph
search_nodeinfo calls erapsedtime, print_progress, nearestnodeinfo, get_cellcenters, set_formattc, timekeeper_
solve_correspondence calls search_nodeinfo
cube2usg calls solve_correspondence