set_cell2faces – Droplets Simulation
set_cell2faces Subroutine
23 statements
Source File
public subroutine set_cell2faces(this)
Uses
terminalControler_m
Type Bound
scf_grid_t
Arguments
Type Intent Optional Attributes Name
class(scf_grid_t), intent(inout) :: this
Calls
Contents
Call graph
set_cell2faces calls cell2faces, face2cells, print_progress, check_range_of_array, set_formattc