set_node_coords – Droplets Simulation
set_node_coords Subroutine
10 statements
Source File
public subroutine set_node_coords(this)
Type Bound
scf_grid_t
Arguments
Type Intent Optional Attributes Name
class(scf_grid_t), intent(inout) :: this
Calls
Contents
Call graph
set_node_coords calls can_x, can_y, can_z, node