simulationSetUp – Droplets Simulation
simulationSetUp Subroutine
42 statements
Source File
public subroutine simulationSetUp(case_name)
Uses
virusDroplet_m
conditionValue_m
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: case_name
Calls
Called by
Contents
None
Call graph
simulationsetup calls read_condition, dropletgenerator_, flowfield_, dropletequationsolver_, read_backup
flowfield_ calls flowfieldunstructuredgrid_
dropletequationsolver_ calls basicparameter_
flowfieldunstructuredgrid_ calls get_dirfrompath
main calls simulationsetup