solve_correspondence – Droplets Simulation
solve_correspondence Subroutine
13 statements
Source File
subroutine solve_correspondence()
格子と節点の対応付けを解決するサブルーチン
Arguments
None
Calls
Called by
Contents
None
Call graph
solve_correspondence calls output_nodeinfo, read_nodeinfo, search_nodeinfo
output_nodeinfo calls get_cubeshape, get_numcube
read_nodeinfo calls get_cubeshape, get_numcube
search_nodeinfo calls erapsedtime, print_progress, nearestnodeinfo, get_cellcenters, set_formattc, timekeeper_
cube2usg calls solve_correspondence