test_sort – Droplets Simulation
test_sort Subroutine
25 statements
Source File
subroutine test_sort(array_correct, sort_mode)
正解配列（ソート済み配列）を引数に取り、それをシャッフルしたのちにソートを行う 正解配列とソート後の配列を比較し、ソートが機能しているかを検証
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: array_correct(:)
character, intent(in) :: sort_mode
Calls
Called by
Contents
None
Call graph
test_sort calls fisheryates_shuffle, real2content, merge_sort, heap_sort
sort_test calls test_sort