cross_product – Droplets Simulation
cross_product Interface
3 statements
Source File
public interface cross_product
Calls
Called by
Contents
Module Procedures
cross_product_dble cross_product_real
Module Procedures
public function cross_product_dble(a, b) result(cross)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: a(3)
double precision, intent(in) :: b(3)
Return Value double precision(3)
public function cross_product_real(a, b) result(cross)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: a(3)
real, intent(in) :: b(3)
Return Value real(3)
Call graph
cross_product calls cross_product_dble, cross_product_real
volume_tetra calls cross_product
insidejudgment_tetra calls volume_tetra
insidejudgment_tetra_check calls volume_tetra
geometry_test calls insidejudgment_tetra
cellcentercalc_test calls insidejudgment_tetra, insidejudgment_tetra_check