read_CSV – Droplets Simulation
read_CSV Interface
3 statements
Source File
public interface read_CSV
CSV読込手続き
Called by
Contents
Module Procedures
read_csv_dble read_csv_int read_csv_char
Module Procedures
private subroutine read_csv_dble(filename, matrix, column, header)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: filename
double precision, intent(inout), allocatable :: matrix(:,:)
integer, intent(in), optional :: column
logical, optional :: header
private subroutine read_csv_int(filename, matrix, column, header)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: filename
integer, intent(inout), allocatable :: matrix(:,:)
integer, intent(in), optional :: column
logical, optional :: header
private subroutine read_csv_char(filename, matrix, column, header)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: filename
character, intent(inout), allocatable :: matrix(:,:)
integer, intent(in), optional :: column
logical, optional :: header
Call graph
get_box_array calls read_csv
boxflowfield calls get_box_array
dropletcount calls get_box_array